# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "mime-4.0.0-zwmL--0gAACndOVlROQeDnM0chfojNDS8tpohlsBqMNy";
    path = fetchzip {
      url = "https://github.com/andrewrk/mime/archive/refs/tags/4.0.0.tar.gz";
      hash = "sha256-2cZGWczKgM0SGnPkAfUg62pTTx29F1waLJC1LnZ6LEM=";
    };
  }
  {
    name = "wayland-0.5.0-dev-lQa1kpfXAQAcgPkLlX_6VLfrYm2j07h1xvxjKbDwy5jk";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland.git";
      rev = "42a9edb1df8efd57cae0d05121ffa94d3df147c2";
      hash = "sha256-cBrNb21V9WPxN02tdtjxdwZ3cb77b3tZy2pf9vQh5Qo=";
    };
  }
  {
    name = "zmime-0.1.3-Mse7galzAAAXYDAj4HG02Ej2uGpNHt7ZzAu6_7l2iiwB";
    path = fetchgit {
      url = "https://github.com/avac74/zmime";
      rev = "5e00cc9cc01b968b9577df3a1cd7e4af440c0e6c";
      hash = "sha256-h7HyKrYFspr6aNG4hue8um+eYpdjwr2PC5/xGMSRH5Y=";
    };
  }
]
